language: ruby
rvm:
  - "1.9.3"
install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install virtualbox-4.3
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
  - sudo dpkg -i vagrant_1.6.5_x86_64.deb
script:
  - ./update
  - sudo vagrant up
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
