#!/bin/bash

(
for i in provision.d/*; do
	echo function $(basename $i) \{
	cat $i | sed s/^/$'\t'/
	echo \}
done
cat provision.in
) > ./provision.sh

if [ ! -z "$1" ]; then
	gist Vagrantfile provision.sh reprovision.sh silab.sh -u ef23edceb8a5709b87d0
	curl -o /dev/null -sL http://documentup.com/mapio/codebox4im/recompile
fi
