#!/bin/bash

j4imversion=$(curl -sL https://raw.githubusercontent.com/mapio/j4im/master/build.xml | grep '"version"' | cut -d = -f 3 | cut -d '"' -f2)
echo "Updating j4im version to '$j4imversion'"

hg ci -m'Auto update version' && hg push

sed -i~ "s/j4imversion=.*/j4imversion=\"$j4imversion\"/" provision.d/j4im_jar reprovision.sh

(
for i in provision.d/*; do
	echo function $(basename $i) \{
	cat $i | sed s/^/$'\t'/
	echo \}
done
cat provision.in
) > ./provision.sh

if [ ! -z "$1" ]; then
	gist Vagrantfile provision.sh reprovision.sh -u ef23edceb8a5709b87d0
	curl -o /dev/null -sL http://documentup.com/mapio/codebox4im/recompile
fi
